### ISSUE TITLE
"ATR-n"  - TS try to measure the point repeatedly while get the "-2" error message in the log

### ISSUE THREAD

**Issue by hrutkabence** [zsiki/ulyxes#18]
With ATR-n code the totalstation try to measure the target more than it should. I have updated the new version of the robot.py, but it didn't help (that's important, because in the log file I noticed the "-2" error message, which means the previous changes not solved the mysterious problem with the prism type).

Other notficiation:  if "PRn" code used in fix points, there are too many measurment because of the "directfaces=2" and "faces=2".
[Ulyxes-issue2.zip](https://github.com/zsiki/ulyxes/files/3089783/Ulyxes-issue2.zip)

**Comment by zsiki** [comment]
Please repeat observations using log level DEBUG.

**Comment by zsiki** [comment]
I've tested robotplus.py. Something strange happens with the instrument. Sometimes the answer to the 2108 RPC call is not complete. There is no error reported in the answer, but the data missing. This case Ulyxes reports error -2.

Details from the log
the good part:
```
2019-04-18 08:49:23,843 DEBUG: message sent: %R1Q,2108:15000,0
2019-04-18 08:49:25,801 DEBUG: message got: R1P,0,0:0,4.913837499905999,4.844871857781991,13.593880965615844
```
the bad part:
```
2019-04-18 08:52:31,646 DEBUG: message sent: %R1Q,2108:15000,0
2019-04-18 08:52:31,703 DEBUG: message got: %R1P,0,0:0
2019-04-18 08:52:31,704 ERROR: error from instrument: -2
```
No observations in the answer to 2108.
I have to debug the code.

**Comment by zsiki** [comment]
Increasing timeout to 60 in serial interface solved the problem.
