### ISSUE TITLE
Can PyAPI be used to send commands to a CS15 that is talking to a TS15

### ISSUE THREAD

**Issue by gursel58** [zsiki/ulyxes#36]
I am just trying to understand communicating with a Leica TS15 and CS15 system and would like to remotely send a command to the CS15 to command the TS15 todo a measurement.
Is that possible ?

**Comment by zsiki** [comment]
For TS15 you need GeoCom license to use PyAPI. As far as I know you cannot buy GeoCom for Leica total stations after TPS 1200 series. You have to make a contract or use the GeoMos.
 I have no chance to test it width TS15, yet. Usually all GeoCom commands work without GeoCom, except those rotate the  instrument :(

**Comment by gursel58** [comment]
Thanks for the information
