### ISSUE TITLE
Compatibility with TS16

### ISSUE THREAD

**Issue by FSet89** [zsiki/ulyxes#43]
Is the PyAPI compatible with TS16? Should I write my own class?

**Comment by zsiki** [comment]
It depends on the GeoCom version and compatibility. Unfortunately I have no experiences with TS16. I coudn't find newer GeoCom manuals which works with TS16. If you have one you can compare the ASCII protocol messages to the ones of the existing classes (LeicaTCA1800, LeicaTCRA1100, LeicaTPS1200).
I suppose you or we should create a new class, I found differences among different Leica total station series.

**Comment by FSet89** [comment]
Can you suggest me a reference for the protocol for the existing classes? Thank you very much

**Comment by zsiki** [comment]
Ulyxes uses GeoCom ASCII commands. For TPS 1200 serie you can find the manual here: https://www.naic.edu/~phil/hardware/theodolites/TPS1200_GeoCOM_Manual.pdf. 
The commands to send start with "%R1Q", the common commands are implemented in the leicameasureunit.py, the other instrument specific tasks are inherited from this and only few method implemented to handle incompatibility and enhanced capabilities. The messages sent to the instrument are created in the methods which names end with Msg.
If you have GeoCom license for your TS16 you should try LeicaTPS1200 class with it to find the incompatibilities.

**Comment by FSet89** [comment]
Where can I get the license?

**Comment by zsiki** [comment]
You can buy one from Leica.

**Comment by FSet89** [comment]
I read that there are three Geocom licenses. Which one should I buy?
GeoCom Imaging TS/MS License key
GeoCom Video Streaming TS/MS License key 
Virtual GeoCom TS/MS License key 

Thank you very much for your support

**Comment by zsiki** [comment]
AFAIK none of them. You need a Robotic license (the basic communication to the instrument using ASCII GeoCom commands). I'm not up to date to the newest total stations, it may be the Robotic license is not extra. On Leica myWorld you may find some information.

**Comment by zsiki** [comment]
I have had experiences with a TS 15 instrument, it has the same GeoCom command as TPS 1200 instruments. Only the GeoCom Robotics License necessary to use with Ulyxes.
